/*Secuencia para el campo ID_TARJETA de la tabla TARJETA*/
CREATE SEQUENCE SEQ_ID_TARJETA START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_PSE de la tabla PSE*/
CREATE SEQUENCE SEQ_ID_PSE START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_PAGO de la tabla PAGO*/
CREATE SEQUENCE SEQ_ID_PAGO START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_PEDIDO de la tabla PEDIDO*/
CREATE SEQUENCE SEQ_ID_PEDIDO START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_PRODUCTO de la tabla PRODUCTO*/
CREATE SEQUENCE SEQ_ID_PRODUCTO START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_AUD_CAL de la tabla AUDITORIA_CALIFICACION*/
CREATE SEQUENCE SEQ_ID_ACAL START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_AUD_VEN de la tabla AUDITORIA_VENTA*/
CREATE SEQUENCE SEQ_ID_AVEN START WITH 100 INCREMENT BY 1;

/*Secuencia para el campo ID_AUD_COM de la tabla AUDITORIA_COMISION*/
CREATE SEQUENCE SEQ_ID_ACOM START WITH 100 INCREMENT BY 1;

