/*Sinonimo para la tabla REPRESENTANTE_VENTA*/
CREATE PUBLIC SYNONYM REPRESENTANTES FOR NATAME.REPRESENTANTE_VENTA;

/*Sinonimo para la tabla HISTORICO_CLASIFICACION*/
CREATE PUBLIC SYNONYM HISTORICO_CLASIFICACIONES FOR NATAME.HISTORICO_CLASIFICACION;

/*Sinonimo para la tabla CLASIFICACION*/
CREATE PUBLIC SYNONYM CLASIFICACIONES FOR NATAME.CLASIFICACION;

/*Sinonimo para la tabla UBICACION*/
CREATE PUBLIC SYNONYM UBICACIONES FOR NATAME.UBICACION;

/*Sinonimo para la tabla REP_VENTA_CLIENTE*/
CREATE PUBLIC SYNONYM REPRESENTANTE_CLIENTES FOR NATAME.REP_VENTA_CLIENTE;

/*Sinonimo para la tabla CLIENTE*/
CREATE PUBLIC SYNONYM CLIENTES FOR NATAME.CLIENTE;

/*Sinonimo para la tabla TARJETA*/
CREATE PUBLIC SYNONYM TARJETAS FOR NATAME.TARJETA;

/*Sinonimo para la tabla PSE*/
CREATE PUBLIC SYNONYM CUENTAS_PSE FOR NATAME.PSE;

/*Sinonimo para la tabla DETALLE_PRODUCTO*/
CREATE PUBLIC SYNONYM VENTAS FOR NATAME.DETALLE_PRODUCTO;

/*Sinonimo para la tabla DETALLE_PRODUCTO*/
CREATE PUBLIC SYNONYM VENTAS FOR NATAME.DETALLE_PRODUCTO;