

CREATE TABLE AUDITORIA_CALIFICACION
(
  ID_ACAL NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_REPRESENTANTE NUMBER(8) NOT NULL 
, CALIFICACION_ANT NUMBER(1)
, CALIFICACION_NUE NUMBER(1)
) ;


CREATE TABLE AUDITORIA_VENTA
(
  ID_AVEN NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_REPRESENTANTE NUMBER(8) NOT NULL  
, VENTA_ANT NUMBER()
, VENTA_NUE NUMBER()
);

CREATE TABLE AUDITORIA_COMISION
(
  ID_ACOM NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_REPRESENTANTE NUMBER(8) NOT NULL  
, COMISION_ANT NUMBER() 
, COMISION_NUE NUMBER() 
);